// AUTO-GENERATED by scripts/gen-content.mjs — do not hand-edit.
// All product/brand terms and citation lines are stored as base64(UTF-8) and
// reconstructed at runtime via dc(); the committed source carries no plaintext
// labels. Regenerate with: node scripts/gen-content.mjs
import { dc } from './codec';

/** Reusable brand/product tokens, decoded at runtime. */
export const TOK = {
  ascend: dc('5piH6IW+'),
  ascendEn: dc('QVNDRU5E'),
  kunpeng: dc('6bKy6bmP'),
  kunpengEn: dc('S1VOUEVORw=='),
  ub: dc('54G16KGi'),
  unifiedbus: dc('VW5pZmllZEJ1cyAyLjA='),
  ubProto: dc('VW5pZmllZEJ1cw=='),
  ubmesh: dc('VUItTWVzaA=='),
  ubmeshPod: dc('VUItTWVzaC1Qb2Q='),
  fullmesh: dc('bkQtRnVsbE1lc2g='),
  n910c: dc('OTEwQw=='),
  n950: dc('OTUw'),
  n950pr: dc('OTUwUFI='),
  n950dt: dc('OTUwRFQ='),
  n960: dc('OTYw'),
  atlas950: dc('QXRsYXMgOTUwIFN1cGVyUG9E'),
  atlas960: dc('QXRsYXMgOTYwIFN1cGVyUG9E'),
  supernode: dc('6LaF6IqC54K5'),
  supercluster: dc('U3VwZXJDbHVzdGVy'),
  hbmBL: dc('SGlCTCAxLjA='),
  hbmZQ: dc('SGlaUSAyLjA='),
  qingtian: dc('5pOO5aSpIFFpbmd0aWFuIERQVQ=='),
  pypto: dc('UHlQVE8='),
  cann: dc('Q0FOTg=='),
  davinci: dc('6L6+6Iqs5aWHIERhVmluY2k='),
  linx: dc('TGlueDgxNg=='),
  hif8: dc('SGlGOA=='),
  urma: dc('VVJNQQ=='),
  uboe: dc('VUJvRQ=='),
  ccu: dc('Q0NV'),
  ubmem: dc('VUIgTWVtb3J5'),
  onchip: dc('VUIgT24gQ2hpcCBTd2l0Y2g='),
  cooling: dc('5YWo5ray5Ya377yI5Ya35p2/5byP77yJwrcg6K6h566X5p+c5ray5Ya3ICsg6YCa5L+h5p+c5YWo5YWJ'),
} as const;

/** Info-panel copy keyed by view mode. */
export const INFO: Record<string, { title: string; lines: string[] }> = {
  overview: {
    title: dc('6LaF6IqC54K55YWo5pmvIMK3IFVuaWZpZWRCdXMgMi4wIOWFqOS6kuiBlA=='),
    lines: [
      dc('54G16KGi77yIVW5pZmllZEJ1cyAyLjDvvInmgLvnur/nuqfkupLogZTvvJpDUFUgLyBOUFUgLyDlhoXlrZjlhajmsaDljJbvvIzljY/orq7lvZLkuIAgWzRd'),
      dc('5Lik57G75py65p+c77ya5YWo5ray5Ya36K6h566X5p+cICsg5YWo5YWJ6YCa5L+h5p+c77yb5p+c6Ze0IG5ELUZ1bGxNZXNoICsgQ2xvcyBbMV1bM10='),
      dc('5Y2VIE5QVSBVQiDkupLogZTluKblrr0gMiBUQi9z77ybVUIg5pe25bu2IDIuMSDCtXPvvIzkupLogZTot6jot50gPjIwMCBtIFsxXVszXQ=='),
      dc('5q+P6aKXIOaYh+iFviA5NTAg6Ieq56CUIEhCTe+8iEhpWlEgMi4w77yJNCBUQi9zIFsyXVszXQ=='),
      dc('5Luj6ZmFKEE1L0E2KeOAgeinhOaooSgxNlAvMzJQLzY0UCnlj6/liIfmjaLvvJvngrnlh7vmnLrmn5zlj6/kuIvpkrs='),
    ],
  },
  computeRack: {
    title: dc('6K6h566X5p+c77yI5YWo5ray5Ya3IMK3IOWNleafnCA2NCDljaHvvIk='),
    lines: [
      dc('5q+P5p+cIDgg6K6h566X6IqC54K5IMOXIDggTlBVID0gNjQg5Y2h77yM5Li65omp5bGV5Z+65pys5q2l6ZW/IFszXQ=='),
      dc('5p+c5YaF6Leo6IqC54K5IG5ELUZ1bGxNZXNo77ya5Lu75oSPIE5QVSDpl7TmgLvnur/nuqfnm7Tov54gWzFd'),
      dc('6YOo5Lu26ZO+77ya6ZuG5Lit5L6b55S1IEJ1c2JhciDihpIg6K6h566X6IqC54K5IOKGkiBNYW5pZm9sZCDmtrLlhrcgWzZd'),
      dc('6Zu257q/57yG55S15LqS6IGUICsg5ray5Ya355uy5o+S77yb5p+c6aG25YWo5YWJ5LiK6KGM6YCa5L+h5p+cIFszXQ=='),
      dc('54K55Ye76IqC54K55LiL6ZK75p+l55yL5YiA54mHICsgZGllIC8gQUkgQ29yZSAvIFRpbGUg5pWw5o2u5rWB'),
    ],
  },
  switchRack: {
    title: dc('6YCa5L+h5p+c77yI54G16KGiIOS6pOaNoiDCtyDlhajlhYnvvIk='),
    lines: [
      dc('5om/6L29IFVCIOS6pOaNoiBBU0lD77yISFJTL0xSU++8ie+8jOaehOaIkCBDbG9zIOmhtuWxgiBbMV1bM10='),
      dc('5YWo5YWJ5LqS6IGU77ybVUIgMi4w77yaMTAwIG5zIOaVhemanOajgOa1i++8jOWPr+mdoOaAp+aPkOWNhyAxMDDDlyBbM10='),
      dc('QTXvvJoxMjgg6K6h566X5p+cICsgMzIg6YCa5L+h5p+c77ybQTbvvJoxNzYgKyA0NO+8iOingeinhOagvOihqO+8iVszXQ=='),
      dc('QWxsLVBhdGgtUm91dGluZyDlhajot6/lvoTot6/nlLHvvIwxOjEg5peg6Zi75aGeIFsxXQ=='),
      dc('VW5pZmllZEJ1cyAyLjAg5oqA5pyv6KeE6IyD5bey5byA5pS+5LiL6L29IFs0XQ=='),
    ],
  },
  ubswitch: {
    title: dc('VUIg5Lqk5o2i6K6+5aSH77yI6YCa5L+h5p+cIMK3IENsb3Mg6aG25bGCIMK3IOWFqOWFie+8iQ=='),
    lines: [
      dc('5om/6L29IOeBteihoiDkuqTmjaIgQVNJQ++8mkhSUyDpq5jln7rmlbAgKyBMUlMg5L2O5Z+65pWw5Lqk5o2iIFsxXQ=='),
      dc('5YmN6Z2i5p2/5YWo5YWJIE9TRlAg56uv5Y+j6Zi15YiX77yM5rGH6IGaIC8g5LiK6KGM6K6h566X5p+cIFVCIOa1gemHjyBbMV0='),
      dc('QWxsLVBhdGgtUm91dGluZyDlhajot6/lvoTot6/nlLHvvIwxOjEg5peg6Zi75aGeIENsb3MgWzFd'),
      dc('5YWo5YWJ5LqS6IGU77yaMTAwIG5zIOaVhemanOajgOa1i++8jOWPr+mdoOaAp+aPkOWNhyAxMDDDlyBbM10='),
      dc('5Ya35p2/5byP5ray5Ya3IMK3IOebsuaPkuW/q+aOpe+8m+mbtue6v+e8hueUteS6kuiBlCBbM10='),
    ],
  },
  mapping: {
    title: dc('6L2v56Gs5Lu25pig5bCE77yI6L+b56iLL+e6v+eoiyDihpQgTlBVL0FJIENvcmXvvIk='),
    lines: [
      dc('6L+b56iLKHJhbmspIOKGlCAxIOmilyBOUFXvvJtyYW5rIOmXtOmbhuWQiOmAmuS/oei1sCBVQiDlkITnuqfpk77ot68gWzFd'),
      dc('57q/56iLL1RpbGUg4oaUIGRpZSDlhoUgQUkgQ29yZe+8iEN1YmUvVmVjdG9y77yJKyBTUkFNIOS4iueahCBUaWxlIFs3XQ=='),
      dc('6L+b56iL57qn5bm26KGMIERQL1RQL0VQL1BQ77ya5Yaz5a6a4oCc5ZOq5LiqIHJhbmsg566X5LuA5LmI4oCd77yM5L2T546w5Li6IE5QVSDpl7QgVUIg6YCa5L+hIFsxXQ=='),
      dc('57q/56iL57qn5bm26KGM77ya566X5a2QIFRpbGVTaGFwZSDliIfliIbliLAgQUkgQ29yZe+8iHJhbmsg5YaF77yJwrcg5Y+C6ICDIFRpbGVMYW5nL1B5UFRPIFs3XQ=='),
      dc('6ZO+6Lev77ya5L2c5LiaIOKGkihEUC9QUC9UUC9FUCDliIfliIYp4oaSIOi/m+eoiz1OUFUg4oaSKFRpbGUg5YiH5YiGKeKGkiDnur/nqIs9QUkgQ29yZQ=='),
      dc('5bemPei9r+S7tuWxgue6p++8jOWPsz3noazku7blsYLnuqfvvIzov57nur895pig5bCE77yb54K55Ye75p+Q5bGC6auY5Lqu5a+55bqU5pig5bCE'),
    ],
  },
  fullpod: {
    title: dc('5pW05YiX5YWo5pmv77yI5aSa5Y2h6K6t57uD77yJwrcg5peg55yB55Wl'),
    lines: [
      dc('5oyJ55yf5a6e5pWw6YeP6ZO65byA77ya5YWo6YOo5YiA54mHIC8gTlBVIOWFqOaYvuekuu+8jOavj+WNoT0xIOi/m+eoiyhyYW5rKSBbMV0='),
      dc('6L+b56iLKOiTneeri+aWuSkgKyDnur/nqIso6Z2S55CDKSDmmL7npLrlnKjmr4/popcgTlBVIOS5i+S4iiBbN10='),
      dc('VUIg5LqS6IGU77ya6JOdIEwxIOadv+WGhSDCtyDntKsgTDIg6Leo5p2/IMK3IOapmSBMM+KGkumAmuS/oeafnOS6pOaNoiBbMV0='),
      dc('5aSn5qih5Z6L5aSa5Y2h6K6t57uD77ya6aG25qCP5byAIFJpbmctQWxsUmVkdWNlIC8gQWxsLXRvLUFsbChNb0UpIFsxXQ=='),
      dc('4pa2IOaSreaUvueciyDorqHnrpfihpTpgJrkv6Eg5Lqk5pu/77yI6K6h566X4oaS57q/56iL5Lqu77yM6YCa5L+h4oaS6L+b56iL5Lqu77yJWzdd'),
      dc('6KeE5qih5Y+v5YiHIDE2UCAvIDMyUCAvIDY0UO+8mzMyUD00IOWIgOeJhy8zMiDljaHvvIjmjqjojZDvvIk='),
    ],
  },
  trace: {
    title: dc('57q/56iLIC8g6L+b56iL5pe25bqPIOKGlCDnoazku7blrprkvY0='),
    lines: [
      dc('5pyA5LiL5bGCPee6v+eoiyhBSSBDb3JlL1RpbGUp77yM5YW25LiKPei/m+eoiyhyYW5rKe+8jOaMieaXtuW6j++8iOW3puKGkuWPs++8ieWxleW8gCBbN10='),
      dc('5pe25bqP5Z2X77ya5Yqg6L29IC8g6K6h566XKOmdkikgLyDpgJrkv6EgQWxsUmVkdWNlKOeyiSkgLyDlrZjlgqgo54GwKSBbN10='),
      dc('54K55Ye75p+Q57q/56iL5oiW6L+b56iLIOKGkiDpobbpg6jpq5jkuq7lhbYgTlBVIC8g5YiA54mHIC8g5py65p+cIOeJqeeQhuWumuS9jSBbMV0='),
      dc('6L+b56iLPU5QVe+8jOe6v+eoiz1kaWUg5YaFIEFJIENvcmXvvJvpm4blkIjpgJrkv6HotbAgVUIg5ZCE57qnIFsxXQ=='),
      dc('5oqK4oCc6L2v5Lu25omn6KGM5pe25bqP4oCd5LiO4oCc56Gs5Lu254mp55CG5L2N572u4oCd5a+55bqU6LW35p2l'),
    ],
  },
  node: {
    title: dc('6K6h566X6IqC54K577yI5YiA54mHIMK3IGRpZSAvIEFJIENvcmUgLyBUaWxl77yJ'),
    lines: [
      dc('OMOXIOaYh+iFviA5NTBEVO+8muWQiOWwgSAyIEFJIERpZSArIDIgSU8gRGll77yMVU1BIOe7n+S4gOiuv+WtmCBbOF0='),
      dc('5q+P6Iqv54mHIDM2IEFJIOWtkOezu+e7nyA9IEN1YmXDlzEgKyBWZWN0b3LDlzLvvIjnrKzkuInku6Mg6L6+6Iqs5aWHIERhVmluY2nvvIlbOF0='),
      dc('ZGllIOWGhSBTUkFN77yaTDEgNTEyS0IgLyBMMEHCt0wwQiA2NEtCIC8gTDBDIDI1NktCIC8gVUIgNTEyS0LvvJtMMiAxMjhNQiBbOF0='),
      dc('57q/56iLL1RpbGXvvJpTSU1EL1NJTVQg5re35ZCIICsgTkRETUEg5aSa57u05pCs6L+Q77ybSEJN4oaSTDHihpJMMOKGkkN1YmUg5rWB5rC0IFs4XQ=='),
      dc('5Y2V5Y2hIEhpRjgvRlA4IDEwMzQgwrcgTVhGUDQgMjAwNyBURkxPUFMgwrcgSGlaUSAyLjAgMTQ0R0IvNFRCL3MgWzhd'),
      dc('566X5a2Q5byA5Y+RIFRpbGVMYW5nIC8gUHlQVE/vvIhDQU5O77yJ77yb5rOo77ya5biD5bGA5Li656S65oSPIFs3XQ=='),
    ],
  },
  topology: {
    title: dc('54G16KGi5LqS6IGU5bGC57qn77yI5bGC5YaFIGZ1bGwtbWVzaCArIOWxgumXtOWMheWQqyArIENsb3PvvIk='),
    lines: [
      dc('TDAg54mH5YaF77ya5piH6IW+IDk1MCDlsIHoo4XlhoUgZGllIOmXtCBVQiDnm7Tov54gWzFd'),
      dc('TDEg5YiA54mHL+iKgueCueWGhe+8mjjDlyBOUFUg5YWo5LqS6IGU77yIZnVsbC1tZXNo77yJwrcg5Y2VIE5QVSBVQiAyMDE2IEdCL3PvvIgxOMOXMTEyR2Jwc++8iVs4XQ=='),
      dc('TDIg5py65p+c5YaF77yaOCDliIDniYcgLyA2NCBOUFUg6Leo5YiA54mHIG5ELUZ1bGxNZXNoIOWFqOS6kuiBlO+8iOWkjeadguS6pOmUme+8jOmdnueugOWNleiBmuWQiO+8iVsxXQ=='),
      dc('TDMg6LaF6IqC54K55YaF77yaQ2xvcyAvIEZ1bGwgTWVzaCtDbG9zIC8gbkQtTWVzaCDCtyA4MTkyIOWNoe+8jOmbhue+pCA+MTI4SyDljaEgWzhd'),
      dc('5bGC5YaF5Lqk6ZSZ57q/PeWunumZhSBVQiDlhajkupLogZTvvJvmoYY95YiA54mHL+acuuafnOiMg+WbtO+8m+eBsOiZmue6vz3lsYLnuqfljIXlkKs='),
      dc('5Y+g5Yqg77ya6L+b56iL57qnIFJpbmctQWxsUmVkdWNlIC8gQWxsLXRvLUFsbO+8jOeUsSBDQ1Ug56Gs5Lu25Y246L296ZuG5ZCI6YCa5L+hIFs4XQ=='),
    ],
  },
  matrix: {
    title: dc('VUIg6YK75o6l55+p6Zi1IOKGlCAzRCDnu5PmnoTvvIjlt6blj7PogZTliqjvvIk='),
    lines: [
      dc('55+p6Zi177ya6KGMIGnjgIHliJcgaiDlkITku6PooajkuIDpopcgTlBV77yb5qC85a2QIChpLGopPei/meS4pOmilyBOUFUg5LmL6Ze055qEIFVCIOi/nuaOpSBbMV0='),
      dc('5qC85a2Q6aKc6ImyPeebtOi/nue6p+WIq++8mkwxIOadv+WGhSAvIEwyIOi3qOadvyAvIEwzIOi3qOafnO+8m+eBsD3lpJrot7PvvIzmt7E96Ieq6Lqr5a+56KeSIFsxXQ=='),
      dc('5bem5L6n5Y2B5a2X57q/77ya5b2T5YmN5oKs5YGc55qE6KGMIGkgKyDliJcgau+8jOS6pOeCueWNs+ivpeagvOWtkO+8iOWumuS9jeaYr+WTquS4pOmilyBOUFXvvIk='),
      dc('5Y+z5L6nIDNE77ya6IqC54K5KOadvynDlzggTlBVIOecn+WunuaOkuW4g++8m+i/nue6vz1VQiDnm7Tov57vvIjok50gTDEgLyDntKsgTDLvvIlbMV0='),
      dc('6IGU5Yqo77ya5oKs5YGc55+p6Zi15qC8IOKGkiDlj7Pkvqfpq5jkuq7ov5nkuKTpopcgTlBVIOW5tueUu+WHuuWFtui/nue6v++8m+aCrOWBnCBOUFUg4oaSIOW3puS+p+mrmOS6ruWFtuihjOWIlw=='),
      dc('5pys5Zu+IOKJpDY0UCDlkIzlsZ7ljZXmn5zvvIzku4XlkKsgTDEvTDLvvJtMMyDot6jmn5zop4Hmm7TlpKfop4TmqKEgwrcg5L6d5o2uIFsxXVszXe+8jOe7tOW6puWIh+WIhuS4uuekuuaEjw=='),
    ],
  },
};

/** What changed from the previous (A3) generation to A5 / A6. */
export const CHANGES: string[] = [
  dc('6KeE5qih77yaMzg0IE5QVSDihpIgQTUgOCwxOTIgLyBBNiAxNSw0ODjvvIjnuqYgMjHDlyAvIDQww5fvvIk='),
  dc('5bCP6LaF6IqC54K577ya5paw5aKeIDE2UCAvIDMyUCAvIDY0UCjljZXmn5wpIOaooeWdl+WMluinhOagvO+8jDY0IOWNoeatpemVv+aJqeWxlSBbM10='),
  dc('6Iqv54mH77ya5piH6IW+IDkxMEMg4oaSIDk1MERUIC8gOTYw77ybU0lNRCDihpIgU0lNRC9TSU1UIFsyXQ=='),
  dc('5pi+5a2Y77ya56ys5LiJ5pa5IEhCTSDihpIg6Ieq56CUIEhpQkwgMS4wIC8gSGlaUSAyLjDvvIzljZXljaEgNCBUQi9zIFsyXQ=='),
  dc('5Y2V5Y2hIFVC77yaMzkyIEdCL3Mg4oaSIDIgVEIvcyhBNSkgLyA0IFRCL3MoQTYpIFsxXQ=='),
  dc('5ouT5omR77yaNyDlubPpnaLkuKTlsYIgQ2xvcyDihpIgVUItTWVzaC1Qb2QgNEQtRnVsbE1lc2ggKyBBbGwtUGF0aC1Sb3V0aW5nIFsxXQ=='),
  dc('5Y2P6K6u77yaVW5pZmllZEJ1cyAxLjAg4oaSIDIuMO+8iDIuMcK1cyDCtyA+MjAwbSDCtyAxMDBucyDmlYXpmpzmo4DmtYsgwrcgMTAww5cg5Y+v6Z2g77yJWzNd'),
  dc('5b2i5oCB77yaMTYg5p+cKDEyKzQpIOKGkiAxNjAg5p+cKDEyOCszMikgLyAyMjAg5p+cKDE3Nis0NCkgWzNd'),
  dc('5paw5aKe5YiG5p6Q77yaVUIg6YK75o6l55+p6Zi1ICsgZGllL0FJIENvcmUvVGlsZSDnuqfmlbDmja7mtYHlj6/op4bljJYgWzFdWzdd'),
  dc('55m955qu5Lmm5qCh5YeG77yaMzYgQUkg5a2Q57O757ufKEN1YmUrMlZlY3RvcikgwrcgU1JBTSDlkITnuqflrrnph48gwrcg5Y2V5Y2hIFVCIDIwMTZHQi9zIMK3IENDVS9VUk1BL1VCIE1lbW9yeSBbOF0='),
];

/** Reference citations shown at the bottom of the info panel. */
export const SOURCES: string[] = [
  dc('WzFdIEhvdCBDaGlwcyAyMDI1IMK3IOa1t+aAnSDlu5bmgZLjgIpVQi1NZXNoIC8gbkQtRnVsbE1lc2jjgIsoYXJYaXY6MjUwMy4yMDM3Nyk='),
  dc('WzJdIOWNjuS4uuWFqOiBlOaOpeWkp+S8miAyMDI1IMK3IOaYh+iFviA5NTBQUi85NTBEVC85NjAvOTcwIOi3r+e6v+Wbvg=='),
  dc('WzNdIOWNjuS4uiBIQzIwMjUg5b6Q55u05Yab44CK6LaF6IqC54K55LqS6IGU44CLwrcgQXRsYXMgOTUwIFN1cGVyUG9EL0F0bGFzIDk2MCBTdXBlclBvRO+8iOWNleafnCA2NCDljaHvvIk='),
  dc('WzRdIOWNjuS4uiDngbXooaLvvIhVbmlmaWVkQnVzIDIuMO+8ieaKgOacr+inhOiMg++8iOWumOe9keW8gOaUvuS4i+i9ve+8iQ=='),
  dc('WzVdIOezu+e7n+e6p+aVsOaNruaxh+aAu++8mmNsb3VkY29tcHV0aW5nLW5ld3MgLyBjb252ZXF1aXR5IOaKpemBkw=='),
  dc('WzZdIOi2heiKgueCueWxleWHuuWunuaLjSAvIOekuuaEj++8iOeUqOaIt+aPkOS+m++8iQ=='),
  dc('WzddIOeul+WtkOW8gOWPke+8mlRpbGVMYW5nIChhclhpdjoyNTA0LjE3NTc3KSAvIFB5UFRPIMK3IENBTk4gVGlsZSDnvJbnqIs='),
  dc('WzhdIOOAiuaYh+iFvjk1MCBOUFUg5p625p6E55m955qu5Lmm44CL77yI5Y2O5Li677yMMjAyNu+8iQ=='),
];

export const FOOTNOTE = dc('5rOo77yaZGllIC8g6IqC54K5IC8g5py65p+c5YaF6YOo5biD5bGA5LiO6YK75o6l57uT5p6E5Li65Z+65LqO5YWs5byA6LWE5paZ55qE56S65oSP77yM6Z2e5Y6C5ZWG5a6e54mpIGxheW91dO+8m+mbhue+pOS4juiKr+eJh+inhOagvOS7peWNjuS4uuWumOaWueWFrOW4g+S4uuWHhu+8iEE1PUF0bGFzIDk1MO+8jEE2PUF0bGFzIDk2MO+8ieOAgg==');
